name 'openvswitch'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures openvswitch'
long_description 'Installs/Configures openvswitch'
version '0.1.0'
